A = """
----
XXX-
X-X-
XXX-
X-X-
X-X-
----
"""

B = """
-----
XXX--
X-X--
XXX--
X--X-
XXXX-
-----
"""

C = """
----
XXX-
X---
X---
X---
XXX-
----
"""

D = """
-----
XXX--
X--X-
X--X-
X--X-
XXX--
-----
"""

E = """
----
XXX-
X---
XXX-
X---
XXX-
----
"""

F = """
----
XXX-
X---
XXX-
X---
X---
----
"""

G = """
-----
XXXX-
X----
X-XX-
X--X-
XXXX-
-----
"""

H = """
----
X-X-
X-X-
XXX-
X-X-
X-X-
----
"""

I = """
----
XXX-
-X--
-X--
-X--
XXX-
----
"""

J = """
----
-XX-
--X-
--X-
X-X-
-X--
----
"""

K = """
----
X--X-
X-X--
XX---
X-X--
X--X-
----
"""

L = """
----
X---
X---
X---
X---
XXX-
----
"""

M = """
------
X---X-
XX-XX-
X-X-X-
X---X-
X---X-
------
"""

N = """
-----
X--X-
XX-X-
X-XX-
X--X-
X--X-
-----
"""

O = """
----
XXX-
X-X-
X-X-
X-X-
XXX-
----
"""

P = """
----
XXX-
X-X-
XXX-
X---
X---
----
"""

Q = """
----
XXX-
X-X-
X-X-
X-X-
XXX-
---X
"""

R = """
----
XXX-
X-X-
XXX-
XX--
X-X-
----
"""

S = """
----
-XX-
X---
-XX-
--X-
XXX-
----
"""

T = """
----
XXX-
-X--
-X--
-X--
-X--
----
"""

U = """
-----
X--X-
X--X-
X--X-
X--X-
XXXX-
-----
"""

V = """
----
X-X-
X-X-
X-X-
X-X-
-X--
----
"""

W = """
------
X---X-
X---X-
X-X-X-
XX-XX-
X---X-
------
"""

X = """
------
X---X-
-X-X--
--X---
-X-X--
X---X-
------
"""

Y = """
----
X-X-
X-X-
-X--
-X--
-X--
----
"""

Z = """
----
XXX-
--X-
-X--
X---
XXX-
----
"""

" " = """
--
--
--
--
--
--
--
"""
